### ISSUE TITLE
ArXiv link broken.

### ISSUE THREAD

**Issue by lassepe** [sisl/MultiAgentAllocationTransit.jl#2]
The ArXiv link in the `README` does not work (yet?).

**Comment by Shushman** [comment]
Yeah, sorry! I wanted to share the code with a few people so I made it public while the ArXiv is still processing (should be up in the next few days). In the meantime, I have a draft on my website, and I've updated the README with this link - http://web.stanford.edu/~shushman/multidrone_delivery_icra2020_extended.pdf

**Comment by Shushman** [comment]
Also, just FYI, basic documentation and cleanup etc. is very much still in progress.
I was just too lazy to add each of those individuals as collabs haha

**Comment by Shushman** [comment]
Ok the arXiv link is up and on the readme!
