### ISSUE TITLE
Problem with Reproducing Code

### ISSUE THREAD

**Issue by aprinaldi-m** [sisl/MultiAgentAllocationTransit.jl#5]
Halo, thank you for your great work. I am interested in your work here.
I have a problem with Reproducing the code.
I want to run  the `multi-drone-routing-example `notebook, but I stuck at `env = MAPFTransitEnv.....` i got a message 

> Field 'aug_trips_fws_dists' has no default, supply it with keyword.

do you have any idea? 

Thank you

**Comment by Shushman** [comment]
Thanks! The answer was actually in the error message, so do make sure for your own understanding that you see what I had to change, beyond just running the code.

I had updated the `mutable struct` arguments for `MAPFTransitEnv`, changing `trips_fws_dists` to `aug_trips_fws_dists` but not the notebook itself. The latest master branch should have the changed call to `MAPFTransitEnv`. Let me know if you have any other issues running it.
