### ISSUE TITLE
unable to setup

### ISSUE THREAD

**Issue by mojtabasji** [sisl/MultiAgentAllocationTransit.jl#6]
Hello

unfortunately i have problem with pkg> instantiate .
when i run instantiate command receive following error:
 ERROR: Did not find path `/home/shushman/.julia/dev/MultiAgentPathFinding` for `MultiAgentPathFinding [42a2a06c]`

can you help me please?

**Comment by mykelk** [comment]
I think the Manifest.toml should be removed from the repo. Right @Shushman ?

**Comment by Shushman** [comment]
Oh no it's needed because of my custom forks. But the Manifest had an incorrect reference to my home directory rather than the github URLfor my repo. I've updated it to the URLs and it should work now. @mojtabasji let me know

**Comment by mojtabasji** [comment]
Yes it works well thanks a lot. @Shushman   , @mykelk
